export interface Flavor {
    name: string;
    bannerColor: string;
    bannerColorLight?: string;
    backgroundImage?: string;
    bannerAccentColor?: string;
    bottleImage: string;
    flavorDescription: string;
    titleColor: string;
    paragraphOneTitle?: string;
    paragraphOne?: string;
    paragraphTwoTitle?: string;
    paragraphTwo?: string;
    paragraphThreeTitle?: string;
    energy?: string;
    fibre?: string;
    saturatedFat?: string;
    protein?: string;
    carbohydrates?: string;
    salt?: string;
};
