import type { Metadata } from "next";
import Navbar from "./layout/Navbar/Navbar";
import "./globals.css"; 
import { bebas, cormorant } from "./fonts/fonts";

export const metadata: Metadata = {
  title: {
    default: "Schlurp",
    template: "%s - Schlurp"
  }, 
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`antialiased ${bebas.variable} ${cormorant.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
