import type { Metadata } from "next";
import Navbar from "./components/layout/Navbar/Navbar";
import "./globals.css"; 
import { bebas, garamond, slab } from "./fonts/fonts";
import MobileNavbar from "./components/layout/MobileNavbar/MobileNavbar";

export const metadata: Metadata = {
  title: {
    default: "Schlurp",
    template: "%s - Schlurp"
  }, 
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`antialiased ${bebas.variable} ${garamond.variable} ${slab.variable}`}>
        <span className="hidden lg:block">
          <Navbar />
        </span>
        <span className="block lg:hidden">
          {/* <MobileNavbar /> */}
        </span>
        {children}
      </body>
    </html>
  );
}
